const wishlistTypes = {
    ADD_TO_WISHLIST: 'ADD_TO_WISHLIST',
    REMOVE_WISHLIST_ITEM: 'REMOVE_WISHLIST_ITEM',
    CREATE_WISHLIST_START: 'CREATE_WISHLIST_START',
    FETCH_WISHLISTS_START: 'FETCH_WISHLISTS_START',
    FETCH_WISHLIST_START: 'FETCH_WISHLIST_START',
    SET_WISHLIST: 'SET_WISHLIST',
    DELETE_WISHLIST_START: 'DELETE_WISHLIST_START',
    CLEAR_WISHLIST: 'CLEAR_WISHLIST'
};

export default wishlistTypes;