const countryList = [
  {
    countryName: "Argentina",
    countryShortCode: "AR",
    regions: [
      { name: "Buenos Aires", value: "B" },
      { name: "Capital Federal", value: "C" },
      { name: "Catamarca", value: "K" },
      { name: "Chaco", value: "H" },
      { name: "Chubut", value: "U" },
      { name: "Córdoba", value: "X" },
      { name: "Corrientes", value: "W" },
      { name: "Entre Ríos", value: "E" },
      { name: "Formosa", value: "P" },
      { name: "Jujuy", value: "Y" },
      { name: "La Pampa", value: "L" },
      { name: "La Rioja", value: "F" },
      { name: "Mendoza", value: "M" },
      { name: "Misiones", value: "N" },
      { name: "Neuquén", value: "Q" },
      { name: "Río Negro", value: "R" },
      { name: "Salta", value: "A" },
      { name: "San Juan", value: "J" },
      { name: "San Luis", value: "D" },
      { name: "Santa Cruz", value: "Z" },
      { name: "Santa Fe", value: "S" },
      { name: "Santiago del Estero", value: "G" },
      { name: "Tierra del Fuego", value: "V" },
      { name: "Tucumán", value: "T" },
    ],
  },
  {
    countryName: "Australia",
    countryShortCode: "AU",
    regions: [
      { name: "Australian Capital Territory", value: "ACT" },
      { name: "New South Wales", value: "NSW" },
      { name: "Northern Territory", value: "NT" },
      { name: "Queensland", value: "QLD" },
      { name: "South Australia", value: "SA" },
      { name: "Tasmania", value: "TAS" },
      { name: "Victoria", value: "VIC" },
      { name: "Western Australia", value: "WA" },
    ],
  },
  {
    countryName: "Brazil",
    countryShortCode: "BR",
    regions: [
      { name: "Acre", value: "AC" },
      { name: "Alagoas", value: "AL" },
      { name: "Amapá", value: "AP" },
      { name: "Amazonas", value: "AM" },
      { name: "Bahia", value: "BA" },
      { name: "Ceará", value: "CE" },
      { name: "Distrito Federal", value: "DF" },
      { name: "Espírito Santo", value: "ES" },
      { name: "Goiás", value: "GO" },
      { name: "Maranhão", value: "MA" },
      { name: "Mato Grosso", value: "MT" },
      { name: "Mato Grosso do Sul", value: "MS" },
      { name: "Minas Gerais", value: "MG" },
      { name: "Pará", value: "PA" },
      { name: "Paraíba", value: "PB" },
      { name: "Paraná", value: "PR" },
      { name: "Pernambuco", value: "PE" },
      { name: "Piauí", value: "PI" },
      { name: "Rio de Janeiro", value: "RJ" },
      { name: "Rio Grande do Norte", value: "RN" },
      { name: "Rio Grande do Sul", value: "RS" },
      { name: "Rondônia", value: "RO" },
      { name: "Roraima", value: "RR" },
      { name: "Santa Catarina", value: "SC" },
      { name: "São Paulo", value: "SP" },
      { name: "Sergipe", value: "SE" },
      { name: "Tocantins", value: "TO" },
    ],
  },
  {
    countryName: "Canada",
    countryShortCode: "CA",
    regions: [
      {
        name: "Alberta",
        shortCode: "AB",
      },
      {
        name: "British Columbia",
        shortCode: "BC",
      },
      {
        name: "Manitoba",
        shortCode: "MB",
      },
      {
        name: "New Brunswick",
        shortCode: "NB",
      },
      {
        name: "Newfoundland and Labrador",
        shortCode: "NL",
      },
      {
        name: "Northwest Territories",
        shortCode: "NT",
      },
      {
        name: "Nova Scotia",
        shortCode: "NS",
      },
      {
        name: "Nunavut",
        shortCode: "NU",
      },
      {
        name: "Ontario",
        shortCode: "ON",
      },
      {
        name: "Prince Edward Island",
        shortCode: "PE",
      },
      {
        name: "Quebec",
        shortCode: "QC",
      },
      {
        name: "Saskatchewan",
        shortCode: "SK",
      },
      {
        name: "Yukon",
        shortCode: "YT",
      },
    ],
  },
  {
    countryName: "China",
    countryShortCode: "CN",
    regions: [
      { name: "Anhui", value: "AH" },
      { name: "Beijing", value: "BJ" },
      { name: "Chongqing", value: "CQ" },
      { name: "Fujian", value: "FJ" },
      { name: "Gansu", value: "GS" },
      { name: "Guangdong", value: "GD" },
      { name: "Guangxi", value: "GX" },
      { name: "Guizhou", value: "GZ" },
      { name: "Hainan", value: "HI" },
      { name: "Hebei", value: "HE" },
      { name: "Heilongjiang", value: "HL" },
      { name: "Henan", value: "HA" },
      { name: "Hong Kong", value: "HK" },
      { name: "Hubei", value: "HB" },
      { name: "Hunan", value: "HN" },
      { name: "Inner Mongolia", value: "NM" },
      { name: "Jiangsu", value: "JS" },
      { name: "Jiangxi", value: "JX" },
      { name: "Jilin", value: "JL" },
      { name: "Liaoning", value: "LN" },
      { name: "Macau", value: "MO" },
      { name: "Ningxia", value: "NX" },
      { name: "Qinghai", value: "QH" },
      { name: "Shaanxi", value: "SN" },
      { name: "Shandong", value: "SD" },
      { name: "Shanghai", value: "SH" },
      { name: "Shanxi", value: "SX" },
      { name: "Sichuan", value: "SC" },
      { name: "Tianjin", value: "TJ" },
      { name: "Tibet", value: "XZ" },
      { name: "Xinjiang", value: "XJ" },
      { name: "Yunnan", value: "YN" },
      { name: "Zhejiang", value: "ZJ" },
    ],
  },
  {
    countryName: "Congo, the Democratic Republic of the (Kinshasa)",
    countryShortCode: "CD",
    regions: [
      { name: "Bandundu", value: "BN" },
      { name: "Bas-Congo", value: "BC" },
      { name: "Équateur", value: "EQ" },
      { name: "Kasaï-Occidental", value: "KE" },
      { name: "Kasaï-Oriental", value: "KW" },
      { name: "Katanga", value: "KA" },
      { name: "Kinshasa", value: "KN" },
      { name: "Maniema", value: "MA" },
      { name: "Nord-Kivu", value: "NK" },
      { name: "Orientale", value: "OR" },
      { name: "Sud-Kivu", value: "SK" },
    ],
  },
  {
    countryName: "Egypt",
    countryShortCode: "EG",
    regions: [
      { name: "Alexandria", value: "ALX" },
      { name: "Aswan", value: "ASN" },
      { name: "Asyout", value: "AST" },
      { name: "Bani Sueif", value: "BNS" },
      { name: "Beheira", value: "BH" },
      { name: "Cairo", value: "C" },
      { name: "Daqahlia", value: "DK" },
      { name: "Dumiat", value: "DT" },
      { name: "El Bahr El Ahmar", value: "BA" },
      { name: "El Ismailia", value: "IS" },
      { name: "El Suez", value: "SUZ" },
      { name: "El Wadi El Gedeed", value: "WAD" },
      { name: "Fayoum", value: "FYM" },
      { name: "Gharbia", value: "GH" },
      { name: "Giza", value: "GZ" },
      { name: "Helwan", value: "HU" },
      { name: "Kafr El Sheikh", value: "KFS" },
      { name: "Luxor", value: "LX" },
      { name: "Matrouh", value: "MT" },
      { name: "Menia", value: "MN" },
      { name: "Menofia", value: "MNF" },
      { name: "North Sinai", value: "SIN" },
      { name: "Port Said", value: "PTS" },
      { name: "Qalubia", value: "KB" },
      { name: "Qena", value: "KN" },
      { name: "Sharqia", value: "SHR" },
      { name: "Sixth of October", value: "SU" },
      { name: "Sohag", value: "SHG" },
      { name: "South Sinai", value: "JS" },
    ],
  },
  {
    countryName: "Germany",
    countryShortCode: "DE",
    regions: [
      { name: "Baden-Württemberg", value: "BW" },
      { name: "Bayern", value: "BY" },
      { name: "Berlin", value: "BE" },
      { name: "Brandenburg", value: "BB" },
      { name: "Bremen", value: "HB" },
      { name: "Hamburg", value: "HH" },
      { name: "Hessen", value: "HE" },
      { name: "Mecklenburg-Vorpommern", value: "MV" },
      { name: "Niedersachsen", value: "NI" },
      { name: "Nordrhein-Westfalen", value: "NW" },
      { name: "Rheinland-Pfalz", value: "RP" },
      { name: "Saarland", value: "SL" },
      { name: "Sachsen", value: "SN" },
      { name: "Sachsen-Anhalt", value: "ST" },
      { name: "Schleswig-Holstein", value: "SH" },
      { name: "Thüringen", value: "TH" },
    ],
  },
  {
    countryName: "Hong Kong",
    countryShortCode: "HK",
    regions: [{ name: "Hong Kong", value: "HK" }],
  },
  {
    countryName: "India",
    countryShortCode: "IN",
    regions: [
      { name: "Andaman and Nicobar Islands", value: "AN" },
      { name: "Andhra Pradesh", value: "AP" },
      { name: "Arunachal Pradesh", value: "AR" },
      { name: "Assam", value: "AS" },
      { name: "Bihar", value: "BR" },
      { name: "Chandigarh", value: "CH" },
      { name: "Chhattisgarh", value: "CT" },
      { name: "Dadra and Nagar Haveli and Daman and Diu", value: "DH" },
      { name: "Delhi", value: "DL" },
      { name: "Goa", value: "GA" },
      { name: "Gujarat", value: "GJ" },
      { name: "Haryana", value: "HR" },
      { name: "Himachal Pradesh", value: "HP" },
      { name: "Jammu and Kashmir", value: "JK" },
      { name: "Jharkhand", value: "JH" },
      { name: "Karnataka", value: "KA" },
      { name: "Kerala", value: "KL" },
      { name: "Ladakh", value: "LA" },
      { name: "Lakshadweep", value: "LD" },
      { name: "Madhya Pradesh", value: "MP" },
      { name: "Maharashtra", value: "MH" },
      { name: "Manipur", value: "MN" },
      { name: "Meghalaya", value: "ML" },
      { name: "Mizoram", value: "MZ" },
      { name: "Nagaland", value: "NL" },
      { name: "Odisha", value: "OR" },
      { name: "Puducherry", value: "PY" },
      { name: "Punjab", value: "PB" },
      { name: "Rajasthan", value: "RJ" },
      { name: "Sikkim", value: "SK" },
      { name: "Tamil Nadu", value: "TN" },
      { name: "Telangana", value: "TG" },
      { name: "Tripura", value: "TR" },
      { name: "Uttarakhand", value: "UT" },
      { name: "Uttar Pradesh", value: "UP" },
      { name: "West Bengal", value: "WB" },
    ],
  },
  {
    countryName: "Indonesia",
    countryShortCode: "ID",
    regions: [
      { name: "Aceh", value: "AC" },
      { name: "Bali", value: "BA" },
      { name: "Bangka Belitung", value: "BB" },
      { name: "Banten", value: "BT" },
      { name: "Bengkulu", value: "BE" },
      { name: "Gorontalo", value: "GO" },
      { name: "Jakarta Raya", value: "JK" },
      { name: "Jambi", value: "JA" },
      { name: "Jawa Barat", value: "JB" },
      { name: "Jawa Tengah", value: "JT" },
      { name: "Jawa Timur", value: "JI" },
      { name: "Kalimantan Barat", value: "KB" },
      { name: "Kalimantan Selatan", value: "KS" },
      { name: "Kalimantan Tengah", value: "KT" },
      { name: "Kalimantan Timur", value: "KI" },
      { name: "Kalimantan Utara", value: "KU" },
      { name: "Kepulauan Riau", value: "KR" },
      { name: "Lampung", value: "LA" },
      { name: "Maluku", value: "MA" },
      { name: "Maluku Utara", value: "MU" },
      { name: "Nusa Tenggara Barat", value: "NB" },
      { name: "Nusa Tenggara Timur", value: "NT" },
      { name: "Papua", value: "PA" },
      { name: "Papua Barat", value: "PB" },
      { name: "Riau", value: "RI" },
      { name: "Sulawesi Selatan", value: "SR" },
      { name: "Sulawesi Tengah", value: "ST" },
      { name: "Sulawesi Tenggara", value: "SG" },
      { name: "Sulawesi Utara", value: "SA" },
      { name: "Sumatera Barat", value: "SB" },
      { name: "Sumatera Selatan", value: "SS" },
      { name: "Sumatera Utara", value: "SU" },
      { name: "Yogyakarta", value: "YO" },
    ],
  },
  {
    countryName: "Japan",
    countryShortCode: "JP",
    regions: [
      { name: "Aichi", value: "23" },
      { name: "Akita", value: "05" },
      { name: "Aomori", value: "02" },
      { name: "Chiba", value: "12" },
      { name: "Ehime", value: "38" },
      { name: "Fukui", value: "18" },
      { name: "Fukuoka", value: "40" },
      { name: "Fukushima", value: "07" },
      { name: "Gifu", value: "21" },
      { name: "Gunma", value: "10" },
      { name: "Hiroshima", value: "34" },
      { name: "Hokkaido", value: "01" },
      { name: "Hyogo", value: "28" },
      { name: "Ibaraki", value: "08" },
      { name: "Ishikawa", value: "17" },
      { name: "Iwate", value: "03" },
      { name: "Kagawa", value: "37" },
      { name: "Kagoshima", value: "46" },
      { name: "Kanagawa", value: "14" },
      { name: "Kochi", value: "39" },
      { name: "Kumamoto", value: "43" },
      { name: "Kyoto", value: "26" },
      { name: "Mie", value: "24" },
      { name: "Miyagi", value: "04" },
      { name: "Miyazaki", value: "45" },
      { name: "Nagano", value: "20" },
      { name: "Nagasaki", value: "42" },
      { name: "Nara", value: "29" },
      { name: "Niigata", value: "15" },
      { name: "Oita", value: "44" },
      { name: "Okayama", value: "33" },
      { name: "Okinawa", value: "47" },
      { name: "Osaka", value: "27" },
      { name: "Saga", value: "41" },
      { name: "Saitama", value: "11" },
      { name: "Shiga", value: "25" },
      { name: "Shimane", value: "32" },
      { name: "Shizuoka", value: "22" },
      { name: "Tochigi", value: "09" },
      { name: "Tokushima", value: "36" },
      { name: "Tokyo", value: "13" },
      { name: "Tottori", value: "31" },
      { name: "Toyama", value: "16" },
      { name: "Wakayama", value: "30" },
      { name: "Yamagata", value: "06" },
      { name: "Yamaguchi", value: "35" },
      { name: "Yamanashi", value: "19" },
    ],
  },
  {
    countryName: "Korea, Republic of",
    countryShortCode: "KR",
    regions: [
      { name: "Chungcheongbuk-do", value: "43" },
      { name: "Chungcheongnam-do", value: "44" },
      { name: "Jeju-teukbyeoljachido", value: "49" },
      { name: "Jeollabuk-do", value: "45" },
      { name: "Jeollanam-do", value: "46" },
      { name: "Incheon-gwangyeoksi", value: "28" },
      { name: "Gangwon-do", value: "42" },
      { name: "Gwangju-gwangyeoksi", value: "29" },
      { name: "Gyeonggi-do", value: "41" },
      { name: "Gyeongsangbuk-do", value: "47" },
      { name: "Gyeongsangnam-do", value: "48" },
      { name: "Busan-gwangyeoksi", value: "26" },
      { name: "Seoul-teukbyeolsi", value: "11" },
      { name: "Sejong-teukbyeoljachisi", value: "50" },
      { name: "Daegu-gwangyeoksi", value: "27" },
      { name: "Daejeon-gwangyeoksi", value: "30" },
      { name: "Ulsan-gwangyeoksi", value: "31" },
    ],
  },
  {
    countryName: "Mexico",
    countryShortCode: "MX",
    regions: [
      { name: "Aguascalientes", value: "AGU" },
      { name: "Baja California", value: "BCN" },
      { name: "Baja California Sur", value: "BCS" },
      { name: "Campeche", value: "CAM" },
      { name: "Ciudad de México", value: "CMX" },
      { name: "Chiapas", value: "CHP" },
      { name: "Chihuahua", value: "CHH" },
      { name: "Coahuila de Zaragoza", value: "COA" },
      { name: "Colima", value: "COL" },
      { name: "Durango", value: "DUR" },
      { name: "Estado de México", value: "MEX" },
      { name: "Guanajuato", value: "GUA" },
      { name: "Guerrero", value: "GRO" },
      { name: "Hidalgo", value: "HID" },
      { name: "Jalisco", value: "JAL" },
      { name: "Michoacán de Ocampo", value: "MIC" },
      { name: "Morelos", value: "MOR" },
      { name: "Nayarit", value: "NAY" },
      { name: "Nuevo León", value: "NLE" },
      { name: "Oaxaca", value: "OAX" },
      { name: "Puebla", value: "PUE" },
      { name: "Querétaro de Arteaga", value: "QUE" },
      { name: "Quintana Roo", value: "ROO" },
      { name: "San Luis Potosí", value: "SLP" },
      { name: "Sinaloa", value: "SIN" },
      { name: "Sonora", value: "SON" },
      { name: "Tabasco", value: "TAB" },
      { name: "Tamaulipas", value: "TAM" },
      { name: "Tlaxcala", value: "TLA" },
      { name: "Veracruz", value: "VER" },
      { name: "Yucatán", value: "YUC" },
      { name: "Zacatecas", value: "ZAC" },
    ],
  },
  {
    countryName: "New Zealand",
    countryShortCode: "NZ",
    regions: [
      { name: "Auckland", value: "AUK" },
      { name: "Bay of Plenty", value: "BOP" },
      { name: "Canterbury", value: "CAN" },
      { name: "Gisborne", value: "GIS" },
      { name: "Hawke's Bay", value: "HKB" },
      { name: "Marlborough", value: "MBH" },
      { name: "Manawatu-Wanganui", value: "MWT" },
      { name: "Northland", value: "NTL" },
      { name: "Nelson", value: "NSN" },
      { name: "Otago", value: "OTA" },
      { name: "Southland", value: "STL" },
      { name: "Taranaki", value: "TKI" },
      { name: "Tasman", value: "TAS" },
      { name: "Waikato", value: "WKO" },
      { name: "Wellington", value: "WGN" },
      { name: "West Coast", value: "WTC" },
      { name: "Chatham Islands Territory", value: "CIT" },
    ],
  },
  {
    countryName: "Nigeria",
    countryShortCode: "NG",
    regions: [
      { name: "Abia", value: "AB" },
      { name: "Abuja Federal Capital Territory", value: "FC" },
      { name: "Adamawa", value: "AD" },
      { name: "Akwa Ibom", value: "AK" },
      { name: "Anambra", value: "AN" },
      { name: "Bauchi", value: "BA" },
      { name: "Bayelsa", value: "BY" },
      { name: "Benue", value: "BE" },
      { name: "Borno", value: "BO" },
      { name: "Cross River", value: "CR" },
      { name: "Delta", value: "DE" },
      { name: "Ebonyi", value: "EB" },
      { name: "Edo", value: "ED" },
      { name: "Ekiti", value: "EK" },
      { name: "Enugu", value: "EN" },
      { name: "Gombe", value: "GO" },
      { name: "Imo", value: "IM" },
      { name: "Jigawa", value: "JI" },
      { name: "Kaduna", value: "KD" },
      { name: "Kano", value: "KN" },
      { name: "Katsina", value: "KT" },
      { name: "Kebbi", value: "KE" },
      { name: "Kogi", value: "KO" },
      { name: "Kwara", value: "KW" },
      { name: "Lagos", value: "LA" },
      { name: "Nasarawa", value: "NA" },
      { name: "Niger", value: "NI" },
      { name: "Ogun", value: "OG" },
      { name: "Ondo", value: "ON" },
      { name: "Osun", value: "OS" },
      { name: "Oyo", value: "OY" },
      { name: "Plateau", value: "PL" },
      { name: "Rivers", value: "RI" },
      { name: "Sokoto", value: "SO" },
      { name: "Taraba", value: "TA" },
      { name: "Yobe", value: "YO" },
      { name: "Zamfara", value: "ZA" },
    ],
  },
  {
    countryName: "Pakistan",
    countryShortCode: "PK",
    regions: [
      { name: "Azad Kashmir", value: "JK" },
      { name: "Balochistan", value: "BA" },
      { name: "Gilgit-Baltistan", value: "GB" },
      { name: "Islamabad", value: "IS" },
      { name: "Khaibar Pakhtunkhwa", value: "KP" },
      { name: "Punjab", value: "PB" },
      { name: "Sindh", value: "SD" },
      { name: "Federally Administered Tribal Areas", value: "TA" },
    ],
  },
  {
    countryName: "Philippines",
    countryShortCode: "PH",
    regions: [
      { name: "Autonomous Region in Muslim Mindanao", value: "PH-14" },
      { name: "Bicol", value: "PH-05" },
      { name: "Cagayan Valley", value: "PH-02" },
      { name: "Calabarzon", value: "PH-40" },
      { name: "Caraga", value: "PH-13" },
      { name: "Central Luzon", value: "PH-03" },
      { name: "Central Visayas", value: "PH-07" },
      { name: "Cordillera Administrative Region", value: "PH-15" },
      { name: "Davao", value: "PH-11" },
      { name: "Eastern Visayas", value: "PH-08" },
      { name: "Ilocos", value: "PH-01" },
      { name: "Mimaropa", value: "PH-41" },
      { name: "National Capital Region", value: "PH-00" },
      { name: "Northern Mindanao", value: "PH-10" },
      { name: "Soccsksargen", value: "PH-12" },
      { name: "Western Visayas", value: "PH-06" },
      { name: "Zamboanga Peninsula", value: "PH-09" },
    ],
  },
  {
    countryName: "South Africa",
    countryShortCode: "ZA",
    regions: [
      { name: "Eastern Cape", value: "EC" },
      { name: "Free State", value: "FS" },
      { name: "Gauteng", value: "GT" },
      { name: "KwaZulu-Natal", value: "NL" },
      { name: "Limpopo", value: "LP" },
      { name: "Mpumalanga", value: "MP" },
      { name: "Northern Cape", value: "NC" },
      { name: "North West", value: "NW" },
      { name: "Western Cape", value: "WC" },
    ],
  },
  {
    countryName: "Switzerland",
    countryShortCode: "CH",
    regions: [
      { name: "Aargau", value: "AG" },
      { name: "Appenzell Ausserrhoden", value: "AR" },
      { name: "Appenzell Innerhoden", value: "AI" },
      { name: "Basel-Landschaft", value: "BL" },
      { name: "Basel-Stadt", value: "BS" },
      { name: "Bern", value: "BE" },
      { name: "Fribourg", value: "FR" },
      { name: "Genève", value: "GE" },
      { name: "Glarus", value: "GL" },
      { name: "Graubünden", value: "GR" },
      { name: "Jura", value: "JU" },
      { name: "Luzern", value: "LU" },
      { name: "Neuchâtel", value: "NE" },
      { name: "Nidwalden", value: "NW" },
      { name: "Obwalden", value: "OW" },
      { name: "Sankt Gallen", value: "SG" },
      { name: "Schaffhausen", value: "SH" },
      { name: "Schwyz", value: "SZ" },
      { name: "Solothurn", value: "SO" },
      { name: "Thurgau", value: "TG" },
      { name: "Ticino", value: "TI" },
      { name: "Uri", value: "UR" },
      { name: "Valais", value: "VS" },
      { name: "Vaud", value: "VD" },
      { name: "Zug", value: "ZG" },
      { name: "Zürich", value: "ZH" },
    ],
  },
  {
    countryName: "Taiwan",
    countryShortCode: "TW",
    regions: [
      { name: "Changhua", value: "CHA" },
      { name: "Chiayi", value: "CYQ" },
      { name: "Hsinchu", value: "HSQ" },
      { name: "Hualien", value: "HUA" },
      { name: "Kaohsiung", value: "KHH" },
      { name: "Keelung", value: "KEE" },
      { name: "Kinmen", value: "KIN" },
      { name: "Lienchiang", value: "LIE" },
      { name: "Miaoli", value: "MIA" },
      { name: "Nantou", value: "NAN" },
      { name: "Penghu", value: "PEN" },
      { name: "New Taipei", value: "NWT" },
      { name: "Pingtung", value: "PIF" },
      { name: "Taichung", value: "TXG" },
      { name: "Tainan", value: "TNN" },
      { name: "Taipei", value: "TPE" },
      { name: "Taitung", value: "TTT" },
      { name: "Taoyuan", value: "TAO" },
      { name: "Yilan", value: "ILA" },
      { name: "Yunlin", value: "YUN" },
    ],
  },
  {
    countryName: "Turkey",
    countryShortCode: "TR",
    regions: [
      { name: "Adana", value: "01" },
      { name: "Adiyaman", value: "02" },
      { name: "Afyonkarahisar", value: "03" },
      { name: "Agri", value: "04" },
      { name: "Aksaray", value: "68" },
      { name: "Amasya", value: "05" },
      { name: "Ankara", value: "06" },
      { name: "Antalya", value: "07" },
      { name: "Ardahan", value: "75" },
      { name: "Artvin", value: "08" },
      { name: "Aydin", value: "09" },
      { name: "Balikesir", value: "10" },
      { name: "Bartin", value: "74" },
      { name: "Batman", value: "72" },
      { name: "Bayburt", value: "69" },
      { name: "Bilecik", value: "11" },
      { name: "Bingol", value: "12" },
      { name: "Bitlis", value: "13" },
      { name: "Bolu", value: "14" },
      { name: "Burdur", value: "15" },
      { name: "Bursa", value: "16" },
      { name: "Canakkale", value: "17" },
      { name: "Cankiri", value: "18" },
      { name: "Corum", value: "19" },
      { name: "Denizli", value: "20" },
      { name: "Diyarbakir", value: "21" },
      { name: "Duzce", value: "81" },
      { name: "Edirne", value: "22" },
      { name: "Elazig", value: "23" },
      { name: "Erzincan", value: "24" },
      { name: "Erzurum", value: "25" },
      { name: "Eskisehir", value: "26" },
      { name: "Gaziantep", value: "27" },
      { name: "Giresun", value: "28" },
      { name: "Gumushane", value: "29" },
      { name: "Hakkari", value: "30" },
      { name: "Hatay", value: "31" },
      { name: "Igdir", value: "76" },
      { name: "Isparta", value: "32" },
      { name: "Istanbul", value: "34" },
      { name: "Izmir", value: "35" },
      { name: "Kahramanmaras", value: "46" },
      { name: "Karabuk", value: "78" },
      { name: "Karaman", value: "70" },
      { name: "Kars", value: "36" },
      { name: "Kastamonu", value: "37" },
      { name: "Kayseri", value: "38" },
      { name: "Kilis", value: "79" },
      { name: "Kirikkale", value: "71" },
      { name: "Kirklareli", value: "39" },
      { name: "Kirsehir", value: "40" },
      { name: "Kocaeli", value: "41" },
      { name: "Konya", value: "42" },
      { name: "Kutahya", value: "43" },
      { name: "Malatya", value: "44" },
      { name: "Manisa", value: "45" },
      { name: "Mardin", value: "47" },
      { name: "Mersin", value: "33" },
      { name: "Mugla", value: "48" },
      { name: "Mus", value: "49" },
      { name: "Nevsehir", value: "50" },
      { name: "Nigde", value: "51" },
      { name: "Ordu", value: "52" },
      { name: "Osmaniye", value: "80" },
      { name: "Rize", value: "53" },
      { name: "Sakarya", value: "54" },
      { name: "Samsun", value: "55" },
      { name: "Sanliurfa", value: "63" },
      { name: "Siirt", value: "56" },
      { name: "Sinop", value: "57" },
      { name: "Sirnak", value: "73" },
      { name: "Sivas", value: "58" },
      { name: "Tekirdag", value: "59" },
      { name: "Tokat", value: "60" },
      { name: "Trabzon", value: "61" },
      { name: "Tunceli", value: "62" },
      { name: "Usak", value: "64" },
      { name: "Van", value: "65" },
      { name: "Yalova", value: "77" },
      { name: "Yozgat", value: "66" },
      { name: "Zonguldak", value: "67" },
    ],
  },
  {
    countryName: "United States",
    countryShortCode: "US",
    regions: [
      { name: "Alabama", value: "AL" },
      { name: "Alaska", value: "AK" },
      { name: "American Samoa", value: "AS" },
      { name: "Arizona", value: "AZ" },
      { name: "Arkansas", value: "AR" },
      { name: "California", value: "CA" },
      { name: "Colorado", value: "CO" },
      { name: "Connecticut", value: "CT" },
      { name: "Delaware", value: "DE" },
      { name: "District of Columbia", value: "DC" },
      { name: "Micronesia", value: "FM" },
      { name: "Florida", value: "FL" },
      { name: "Georgia", value: "GA" },
      { name: "Guam", value: "GU" },
      { name: "Hawaii", value: "HI" },
      { name: "Idaho", value: "ID" },
      { name: "Illinois", value: "IL" },
      { name: "Indiana", value: "IN" },
      { name: "Iowa", value: "IA" },
      { name: "Kansas", value: "KS" },
      { name: "Kentucky", value: "KY" },
      { name: "Louisiana", value: "LA" },
      { name: "Maine", value: "ME" },
      { name: "Marshall Islands", value: "MH" },
      { name: "Maryland", value: "MD" },
      { name: "Massachusetts", value: "MA" },
      { name: "Michigan", value: "MI" },
      { name: "Minnesota", value: "MN" },
      { name: "Mississippi", value: "MS" },
      { name: "Missouri", value: "MO" },
      { name: "Montana", value: "MT" },
      { name: "Nebraska", value: "NE" },
      { name: "Nevada", value: "NV" },
      { name: "New Hampshire", value: "NH" },
      { name: "New Jersey", value: "NJ" },
      { name: "New Mexico", value: "NM" },
      { name: "New York", value: "NY" },
      { name: "North Carolina", value: "NC" },
      { name: "North Dakota", value: "ND" },
      { name: "Northern Mariana Islands", value: "MP" },
      { name: "Ohio", value: "OH" },
      { name: "Oklahoma", value: "OK" },
      { name: "Oregon", value: "OR" },
      { name: "Palau", value: "PW" },
      { name: "Pennsylvania", value: "PA" },
      { name: "Puerto Rico", value: "PR" },
      { name: "Rhode Island", value: "RI" },
      { name: "South Carolina", value: "SC" },
      { name: "South Dakota", value: "SD" },
      { name: "Tennessee", value: "TN" },
      { name: "Texas", value: "TX" },
      { name: "Utah", value: "UT" },
      { name: "Vermont", value: "VT" },
      { name: "Virgin Islands", value: "VI" },
      { name: "Virginia", value: "VA" },
      { name: "Washington", value: "WA" },
      { name: "West Virginia", value: "WV" },
      { name: "Wisconsin", value: "WI" },
      { name: "Wyoming", value: "WY" },
      { name: "Armed Forces Americas", value: "AA" },
      {
        name: "Armed Forces Europe, Canada, Africa and Middle East",
        value: "AE",
      },
      { name: "Armed Forces Pacific", value: "AP" },
    ],
  },
  {
    countryName: "Vietnam",
    countryShortCode: "VN",
    regions: [
      { name: "An Giang", value: "44" },
      { name: "Bà Rịa - Vũng Tàu", value: "43" },
      { name: "Bình Dương", value: "57" },
      { name: "Bình Phước", value: "58" },
      { name: "Bình Định", value: "31" },
      { name: "Bình Thuận", value: "40" },
      { name: "Bạc Liêu", value: "55" },
      { name: "Bắc Giang", value: "54" },
      { name: "Bắc Kạn", value: "53" },
      { name: "Bắc Ninh", value: "56" },
      { name: "Bến Tre", value: "50" },
      { name: "Cao Bằng", value: "04" },
      { name: "Cà Mau", value: "59" },
      { name: "Đắk Lắk", value: "33" },
      { name: "Đắk Nông", value: "72" },
      { name: "Điện Biên", value: "71" },
      { name: "Đồng Nai", value: "39" },
      { name: "Đồng Tháp", value: "45" },
      { name: "Gia Lai", value: "30" },
      { name: "Hà Giang", value: "03" },
      { name: "Hà Nam", value: "63" },
      { name: "Hà Tây", value: "15" },
      { name: "Hà Tĩnh", value: "23" },
      { name: "Hải Dương", value: "61" },
      { name: "Hậu Giang", value: "73" },
      { name: "Hòa Bình", value: "14" },
      { name: "Hưng Yên", value: "66" },
      { name: "Khánh Hòa", value: "34" },
      { name: "Kiên Giang", value: "47" },
      { name: "Kon Tum", value: "28" },
      { name: "Lai Châu", value: "01" },
      { name: "Lâm Đồng", value: "35" },
      { name: "Lạng Sơn", value: "09" },
      { name: "Lào Cai", value: "02" },
      { name: "Long An", value: "41" },
      { name: "Nam Định", value: "67" },
      { name: "Nghệ An", value: "22" },
      { name: "Ninh Bình", value: "18" },
      { name: "Ninh Thuận", value: "36" },
      { name: "Phú Thọ", value: "68" },
      { name: "Phú Yên", value: "32" },
      { name: "Quảng Bình", value: "24" },
      { name: "Quảng Nam", value: "27" },
      { name: "Quảng Ngãi", value: "29" },
      { name: "Quảng Ninh", value: "13" },
      { name: "Quảng Trị", value: "25" },
      { name: "Sóc Trăng", value: "52" },
      { name: "Sơn La", value: "05" },
      { name: "Tây Ninh", value: "37" },
      { name: "Thái Bình", value: "20" },
      { name: "Thái Nguyên", value: "69" },
      { name: "Thanh Hóa", value: "21" },
      { name: "Thừa Thiên–Huế", value: "26" },
      { name: "Tiền Giang", value: "46" },
      { name: "Trà Vinh", value: "51" },
      { name: "Tuyên Quang", value: "07" },
      { name: "Vĩnh Long", value: "49" },
      { name: "Vĩnh Phúc", value: "70" },
      { name: "Yên Bái", value: "06" },
      { name: "Cần Thơ", value: "CT" },
      { name: "Đà Nẵng", value: "DN" },
      { name: "Hà Nội", value: "HN" },
      { name: "Hải Phòng", value: "HP" },
      { name: "Hồ Chí Minh (Sài Gòn)", value: "SG" },
    ],
  },
];

export default countryList;
