const countryList = [
  {
    countryName: "Argentina",
    countryShortCode: "AR",
    regions: [
      { name: "Buenos Aires", shortCode: "B" },
      { name: "Capital Federal", shortCode: "C" },
      { name: "Catamarca", shortCode: "K" },
      { name: "Chaco", shortCode: "H" },
      { name: "Chubut", shortCode: "U" },
      { name: "Córdoba", shortCode: "X" },
      { name: "Corrientes", shortCode: "W" },
      { name: "Entre Ríos", shortCode: "E" },
      { name: "Formosa", shortCode: "P" },
      { name: "Jujuy", shortCode: "Y" },
      { name: "La Pampa", shortCode: "L" },
      { name: "La Rioja", shortCode: "F" },
      { name: "Mendoza", shortCode: "M" },
      { name: "Misiones", shortCode: "N" },
      { name: "Neuquén", shortCode: "Q" },
      { name: "Río Negro", shortCode: "R" },
      { name: "Salta", shortCode: "A" },
      { name: "San Juan", shortCode: "J" },
      { name: "San Luis", shortCode: "D" },
      { name: "Santa Cruz", shortCode: "Z" },
      { name: "Santa Fe", shortCode: "S" },
      { name: "Santiago del Estero", shortCode: "G" },
      { name: "Tierra del Fuego", shortCode: "V" },
      { name: "Tucumán", shortCode: "T" },
    ],
  },
  {
    countryName: "Australia",
    countryShortCode: "AU",
    regions: [
      { name: "Australian Capital Territory", shortCode: "ACT" },
      { name: "New South Wales", shortCode: "NSW" },
      { name: "Northern Territory", shortCode: "NT" },
      { name: "Queensland", shortCode: "QLD" },
      { name: "South Australia", shortCode: "SA" },
      { name: "Tasmania", shortCode: "TAS" },
      { name: "Victoria", shortCode: "VIC" },
      { name: "Western Australia", shortCode: "WA" },
    ],
  },
  {
    countryName: "Brazil",
    countryShortCode: "BR",
    regions: [
      { name: "Acre", shortCode: "AC" },
      { name: "Alagoas", shortCode: "AL" },
      { name: "Amapá", shortCode: "AP" },
      { name: "Amazonas", shortCode: "AM" },
      { name: "Bahia", shortCode: "BA" },
      { name: "Ceará", shortCode: "CE" },
      { name: "Distrito Federal", shortCode: "DF" },
      { name: "Espírito Santo", shortCode: "ES" },
      { name: "Goiás", shortCode: "GO" },
      { name: "Maranhão", shortCode: "MA" },
      { name: "Mato Grosso", shortCode: "MT" },
      { name: "Mato Grosso do Sul", shortCode: "MS" },
      { name: "Minas Gerais", shortCode: "MG" },
      { name: "Pará", shortCode: "PA" },
      { name: "Paraíba", shortCode: "PB" },
      { name: "Paraná", shortCode: "PR" },
      { name: "Pernambuco", shortCode: "PE" },
      { name: "Piauí", shortCode: "PI" },
      { name: "Rio de Janeiro", shortCode: "RJ" },
      { name: "Rio Grande do Norte", shortCode: "RN" },
      { name: "Rio Grande do Sul", shortCode: "RS" },
      { name: "Rondônia", shortCode: "RO" },
      { name: "Roraima", shortCode: "RR" },
      { name: "Santa Catarina", shortCode: "SC" },
      { name: "São Paulo", shortCode: "SP" },
      { name: "Sergipe", shortCode: "SE" },
      { name: "Tocantins", shortCode: "TO" },
    ],
  },
  {
    countryName: "China",
    countryShortCode: "CN",
    regions: [
      { name: "Anhui", shortCode: "AH" },
      { name: "Beijing", shortCode: "BJ" },
      { name: "Chongqing", shortCode: "CQ" },
      { name: "Fujian", shortCode: "FJ" },
      { name: "Gansu", shortCode: "GS" },
      { name: "Guangdong", shortCode: "GD" },
      { name: "Guangxi", shortCode: "GX" },
      { name: "Guizhou", shortCode: "GZ" },
      { name: "Hainan", shortCode: "HI" },
      { name: "Hebei", shortCode: "HE" },
      { name: "Heilongjiang", shortCode: "HL" },
      { name: "Henan", shortCode: "HA" },
      { name: "Hong Kong", shortCode: "HK" },
      { name: "Hubei", shortCode: "HB" },
      { name: "Hunan", shortCode: "HN" },
      { name: "Inner Mongolia", shortCode: "NM" },
      { name: "Jiangsu", shortCode: "JS" },
      { name: "Jiangxi", shortCode: "JX" },
      { name: "Jilin", shortCode: "JL" },
      { name: "Liaoning", shortCode: "LN" },
      { name: "Macau", shortCode: "MO" },
      { name: "Ningxia", shortCode: "NX" },
      { name: "Qinghai", shortCode: "QH" },
      { name: "Shaanxi", shortCode: "SN" },
      { name: "Shandong", shortCode: "SD" },
      { name: "Shanghai", shortCode: "SH" },
      { name: "Shanxi", shortCode: "SX" },
      { name: "Sichuan", shortCode: "SC" },
      { name: "Tianjin", shortCode: "TJ" },
      { name: "Tibet", shortCode: "XZ" },
      { name: "Xinjiang", shortCode: "XJ" },
      { name: "Yunnan", shortCode: "YN" },
      { name: "Zhejiang", shortCode: "ZJ" },
    ],
  },
  {
    countryName: "Congo, the Democratic Republic of the (Kinshasa)",
    countryShortCode: "CD",
    regions: [
      { name: "Bandundu", shortCode: "BN" },
      { name: "Bas-Congo", shortCode: "BC" },
      { name: "Équateur", shortCode: "EQ" },
      { name: "Kasaï-Occidental", shortCode: "KE" },
      { name: "Kasaï-Oriental", shortCode: "KW" },
      { name: "Katanga", shortCode: "KA" },
      { name: "Kinshasa", shortCode: "KN" },
      { name: "Maniema", shortCode: "MA" },
      { name: "Nord-Kivu", shortCode: "NK" },
      { name: "Orientale", shortCode: "OR" },
      { name: "Sud-Kivu", shortCode: "SK" },
    ],
  },
  {
    countryName: "Egypt",
    countryShortCode: "EG",
    regions: [
      { name: "Alexandria", shortCode: "ALX" },
      { name: "Aswan", shortCode: "ASN" },
      { name: "Asyout", shortCode: "AST" },
      { name: "Bani Sueif", shortCode: "BNS" },
      { name: "Beheira", shortCode: "BH" },
      { name: "Cairo", shortCode: "C" },
      { name: "Daqahlia", shortCode: "DK" },
      { name: "Dumiat", shortCode: "DT" },
      { name: "El Bahr El Ahmar", shortCode: "BA" },
      { name: "El Ismailia", shortCode: "IS" },
      { name: "El Suez", shortCode: "SUZ" },
      { name: "El Wadi El Gedeed", shortCode: "WAD" },
      { name: "Fayoum", shortCode: "FYM" },
      { name: "Gharbia", shortCode: "GH" },
      { name: "Giza", shortCode: "GZ" },
      { name: "Helwan", shortCode: "HU" },
      { name: "Kafr El Sheikh", shortCode: "KFS" },
      { name: "Luxor", shortCode: "LX" },
      { name: "Matrouh", shortCode: "MT" },
      { name: "Menia", shortCode: "MN" },
      { name: "Menofia", shortCode: "MNF" },
      { name: "North Sinai", shortCode: "SIN" },
      { name: "Port Said", shortCode: "PTS" },
      { name: "Qalubia", shortCode: "KB" },
      { name: "Qena", shortCode: "KN" },
      { name: "Sharqia", shortCode: "SHR" },
      { name: "Sixth of October", shortCode: "SU" },
      { name: "Sohag", shortCode: "SHG" },
      { name: "South Sinai", shortCode: "JS" },
    ],
  },
  {
    countryName: "Germany",
    countryShortCode: "DE",
    regions: [
      { name: "Baden-Württemberg", shortCode: "BW" },
      { name: "Bayern", shortCode: "BY" },
      { name: "Berlin", shortCode: "BE" },
      { name: "Brandenburg", shortCode: "BB" },
      { name: "Bremen", shortCode: "HB" },
      { name: "Hamburg", shortCode: "HH" },
      { name: "Hessen", shortCode: "HE" },
      { name: "Mecklenburg-Vorpommern", shortCode: "MV" },
      { name: "Niedersachsen", shortCode: "NI" },
      { name: "Nordrhein-Westfalen", shortCode: "NW" },
      { name: "Rheinland-Pfalz", shortCode: "RP" },
      { name: "Saarland", shortCode: "SL" },
      { name: "Sachsen", shortCode: "SN" },
      { name: "Sachsen-Anhalt", shortCode: "ST" },
      { name: "Schleswig-Holstein", shortCode: "SH" },
      { name: "Thüringen", shortCode: "TH" },
    ],
  },
  {
    countryName: "Hong Kong",
    countryShortCode: "HK",
    regions: [{ name: "Hong Kong", shortCode: "HK" }],
  },
  {
    countryName: "India",
    countryShortCode: "IN",
    regions: [
      { name: "Andaman and Nicobar Islands", shortCode: "AN" },
      { name: "Andhra Pradesh", shortCode: "AP" },
      { name: "Arunachal Pradesh", shortCode: "AR" },
      { name: "Assam", shortCode: "AS" },
      { name: "Bihar", shortCode: "BR" },
      { name: "Chandigarh", shortCode: "CH" },
      { name: "Chhattisgarh", shortCode: "CT" },
      { name: "Dadra and Nagar Haveli and Daman and Diu", shortCode: "DH" },
      { name: "Delhi", shortCode: "DL" },
      { name: "Goa", shortCode: "GA" },
      { name: "Gujarat", shortCode: "GJ" },
      { name: "Haryana", shortCode: "HR" },
      { name: "Himachal Pradesh", shortCode: "HP" },
      { name: "Jammu and Kashmir", shortCode: "JK" },
      { name: "Jharkhand", shortCode: "JH" },
      { name: "Karnataka", shortCode: "KA" },
      { name: "Kerala", shortCode: "KL" },
      { name: "Ladakh", shortCode: "LA" },
      { name: "Lakshadweep", shortCode: "LD" },
      { name: "Madhya Pradesh", shortCode: "MP" },
      { name: "Maharashtra", shortCode: "MH" },
      { name: "Manipur", shortCode: "MN" },
      { name: "Meghalaya", shortCode: "ML" },
      { name: "Mizoram", shortCode: "MZ" },
      { name: "Nagaland", shortCode: "NL" },
      { name: "Odisha", shortCode: "OR" },
      { name: "Puducherry", shortCode: "PY" },
      { name: "Punjab", shortCode: "PB" },
      { name: "Rajasthan", shortCode: "RJ" },
      { name: "Sikkim", shortCode: "SK" },
      { name: "Tamil Nadu", shortCode: "TN" },
      { name: "Telangana", shortCode: "TG" },
      { name: "Tripura", shortCode: "TR" },
      { name: "Uttarakhand", shortCode: "UT" },
      { name: "Uttar Pradesh", shortCode: "UP" },
      { name: "West Bengal", shortCode: "WB" },
    ],
  },
  {
    countryName: "Indonesia",
    countryShortCode: "ID",
    regions: [
      { name: "Aceh", shortCode: "AC" },
      { name: "Bali", shortCode: "BA" },
      { name: "Bangka Belitung", shortCode: "BB" },
      { name: "Banten", shortCode: "BT" },
      { name: "Bengkulu", shortCode: "BE" },
      { name: "Gorontalo", shortCode: "GO" },
      { name: "Jakarta Raya", shortCode: "JK" },
      { name: "Jambi", shortCode: "JA" },
      { name: "Jawa Barat", shortCode: "JB" },
      { name: "Jawa Tengah", shortCode: "JT" },
      { name: "Jawa Timur", shortCode: "JI" },
      { name: "Kalimantan Barat", shortCode: "KB" },
      { name: "Kalimantan Selatan", shortCode: "KS" },
      { name: "Kalimantan Tengah", shortCode: "KT" },
      { name: "Kalimantan Timur", shortCode: "KI" },
      { name: "Kalimantan Utara", shortCode: "KU" },
      { name: "Kepulauan Riau", shortCode: "KR" },
      { name: "Lampung", shortCode: "LA" },
      { name: "Maluku", shortCode: "MA" },
      { name: "Maluku Utara", shortCode: "MU" },
      { name: "Nusa Tenggara Barat", shortCode: "NB" },
      { name: "Nusa Tenggara Timur", shortCode: "NT" },
      { name: "Papua", shortCode: "PA" },
      { name: "Papua Barat", shortCode: "PB" },
      { name: "Riau", shortCode: "RI" },
      { name: "Sulawesi Selatan", shortCode: "SR" },
      { name: "Sulawesi Tengah", shortCode: "ST" },
      { name: "Sulawesi Tenggara", shortCode: "SG" },
      { name: "Sulawesi Utara", shortCode: "SA" },
      { name: "Sumatera Barat", shortCode: "SB" },
      { name: "Sumatera Selatan", shortCode: "SS" },
      { name: "Sumatera Utara", shortCode: "SU" },
      { name: "Yogyakarta", shortCode: "YO" },
    ],
  },
  {
    countryName: "Japan",
    countryShortCode: "JP",
    regions: [
      { name: "Aichi", shortCode: "23" },
      { name: "Akita", shortCode: "05" },
      { name: "Aomori", shortCode: "02" },
      { name: "Chiba", shortCode: "12" },
      { name: "Ehime", shortCode: "38" },
      { name: "Fukui", shortCode: "18" },
      { name: "Fukuoka", shortCode: "40" },
      { name: "Fukushima", shortCode: "07" },
      { name: "Gifu", shortCode: "21" },
      { name: "Gunma", shortCode: "10" },
      { name: "Hiroshima", shortCode: "34" },
      { name: "Hokkaido", shortCode: "01" },
      { name: "Hyogo", shortCode: "28" },
      { name: "Ibaraki", shortCode: "08" },
      { name: "Ishikawa", shortCode: "17" },
      { name: "Iwate", shortCode: "03" },
      { name: "Kagawa", shortCode: "37" },
      { name: "Kagoshima", shortCode: "46" },
      { name: "Kanagawa", shortCode: "14" },
      { name: "Kochi", shortCode: "39" },
      { name: "Kumamoto", shortCode: "43" },
      { name: "Kyoto", shortCode: "26" },
      { name: "Mie", shortCode: "24" },
      { name: "Miyagi", shortCode: "04" },
      { name: "Miyazaki", shortCode: "45" },
      { name: "Nagano", shortCode: "20" },
      { name: "Nagasaki", shortCode: "42" },
      { name: "Nara", shortCode: "29" },
      { name: "Niigata", shortCode: "15" },
      { name: "Oita", shortCode: "44" },
      { name: "Okayama", shortCode: "33" },
      { name: "Okinawa", shortCode: "47" },
      { name: "Osaka", shortCode: "27" },
      { name: "Saga", shortCode: "41" },
      { name: "Saitama", shortCode: "11" },
      { name: "Shiga", shortCode: "25" },
      { name: "Shimane", shortCode: "32" },
      { name: "Shizuoka", shortCode: "22" },
      { name: "Tochigi", shortCode: "09" },
      { name: "Tokushima", shortCode: "36" },
      { name: "Tokyo", shortCode: "13" },
      { name: "Tottori", shortCode: "31" },
      { name: "Toyama", shortCode: "16" },
      { name: "Wakayama", shortCode: "30" },
      { name: "Yamagata", shortCode: "06" },
      { name: "Yamaguchi", shortCode: "35" },
      { name: "Yamanashi", shortCode: "19" },
    ],
  },
  {
    countryName: "Korea, Republic of",
    countryShortCode: "KR",
    regions: [
      { name: "Chungcheongbuk-do", shortCode: "43" },
      { name: "Chungcheongnam-do", shortCode: "44" },
      { name: "Jeju-teukbyeoljachido", shortCode: "49" },
      { name: "Jeollabuk-do", shortCode: "45" },
      { name: "Jeollanam-do", shortCode: "46" },
      { name: "Incheon-gwangyeoksi", shortCode: "28" },
      { name: "Gangwon-do", shortCode: "42" },
      { name: "Gwangju-gwangyeoksi", shortCode: "29" },
      { name: "Gyeonggi-do", shortCode: "41" },
      { name: "Gyeongsangbuk-do", shortCode: "47" },
      { name: "Gyeongsangnam-do", shortCode: "48" },
      { name: "Busan-gwangyeoksi", shortCode: "26" },
      { name: "Seoul-teukbyeolsi", shortCode: "11" },
      { name: "Sejong-teukbyeoljachisi", shortCode: "50" },
      { name: "Daegu-gwangyeoksi", shortCode: "27" },
      { name: "Daejeon-gwangyeoksi", shortCode: "30" },
      { name: "Ulsan-gwangyeoksi", shortCode: "31" },
    ],
  },
  {
    countryName: "Mexico",
    countryShortCode: "MX",
    regions: [
      { name: "Aguascalientes", shortCode: "AGU" },
      { name: "Baja California", shortCode: "BCN" },
      { name: "Baja California Sur", shortCode: "BCS" },
      { name: "Campeche", shortCode: "CAM" },
      { name: "Ciudad de México", shortCode: "CMX" },
      { name: "Chiapas", shortCode: "CHP" },
      { name: "Chihuahua", shortCode: "CHH" },
      { name: "Coahuila de Zaragoza", shortCode: "COA" },
      { name: "Colima", shortCode: "COL" },
      { name: "Durango", shortCode: "DUR" },
      { name: "Estado de México", shortCode: "MEX" },
      { name: "Guanajuato", shortCode: "GUA" },
      { name: "Guerrero", shortCode: "GRO" },
      { name: "Hidalgo", shortCode: "HID" },
      { name: "Jalisco", shortCode: "JAL" },
      { name: "Michoacán de Ocampo", shortCode: "MIC" },
      { name: "Morelos", shortCode: "MOR" },
      { name: "Nayarit", shortCode: "NAY" },
      { name: "Nuevo León", shortCode: "NLE" },
      { name: "Oaxaca", shortCode: "OAX" },
      { name: "Puebla", shortCode: "PUE" },
      { name: "Querétaro de Arteaga", shortCode: "QUE" },
      { name: "Quintana Roo", shortCode: "ROO" },
      { name: "San Luis Potosí", shortCode: "SLP" },
      { name: "Sinaloa", shortCode: "SIN" },
      { name: "Sonora", shortCode: "SON" },
      { name: "Tabasco", shortCode: "TAB" },
      { name: "Tamaulipas", shortCode: "TAM" },
      { name: "Tlaxcala", shortCode: "TLA" },
      { name: "Veracruz", shortCode: "VER" },
      { name: "Yucatán", shortCode: "YUC" },
      { name: "Zacatecas", shortCode: "ZAC" },
    ],
  },
  {
    countryName: "New Zealand",
    countryShortCode: "NZ",
    regions: [
      { name: "Auckland", shortCode: "AUK" },
      { name: "Bay of Plenty", shortCode: "BOP" },
      { name: "Canterbury", shortCode: "CAN" },
      { name: "Gisborne", shortCode: "GIS" },
      { name: "Hawke's Bay", shortCode: "HKB" },
      { name: "Marlborough", shortCode: "MBH" },
      { name: "Manawatu-Wanganui", shortCode: "MWT" },
      { name: "Northland", shortCode: "NTL" },
      { name: "Nelson", shortCode: "NSN" },
      { name: "Otago", shortCode: "OTA" },
      { name: "Southland", shortCode: "STL" },
      { name: "Taranaki", shortCode: "TKI" },
      { name: "Tasman", shortCode: "TAS" },
      { name: "Waikato", shortCode: "WKO" },
      { name: "Wellington", shortCode: "WGN" },
      { name: "West Coast", shortCode: "WTC" },
      { name: "Chatham Islands Territory", shortCode: "CIT" },
    ],
  },
  {
    countryName: "Nigeria",
    countryShortCode: "NG",
    regions: [
      { name: "Abia", shortCode: "AB" },
      { name: "Abuja Federal Capital Territory", shortCode: "FC" },
      { name: "Adamawa", shortCode: "AD" },
      { name: "Akwa Ibom", shortCode: "AK" },
      { name: "Anambra", shortCode: "AN" },
      { name: "Bauchi", shortCode: "BA" },
      { name: "Bayelsa", shortCode: "BY" },
      { name: "Benue", shortCode: "BE" },
      { name: "Borno", shortCode: "BO" },
      { name: "Cross River", shortCode: "CR" },
      { name: "Delta", shortCode: "DE" },
      { name: "Ebonyi", shortCode: "EB" },
      { name: "Edo", shortCode: "ED" },
      { name: "Ekiti", shortCode: "EK" },
      { name: "Enugu", shortCode: "EN" },
      { name: "Gombe", shortCode: "GO" },
      { name: "Imo", shortCode: "IM" },
      { name: "Jigawa", shortCode: "JI" },
      { name: "Kaduna", shortCode: "KD" },
      { name: "Kano", shortCode: "KN" },
      { name: "Katsina", shortCode: "KT" },
      { name: "Kebbi", shortCode: "KE" },
      { name: "Kogi", shortCode: "KO" },
      { name: "Kwara", shortCode: "KW" },
      { name: "Lagos", shortCode: "LA" },
      { name: "Nasarawa", shortCode: "NA" },
      { name: "Niger", shortCode: "NI" },
      { name: "Ogun", shortCode: "OG" },
      { name: "Ondo", shortCode: "ON" },
      { name: "Osun", shortCode: "OS" },
      { name: "Oyo", shortCode: "OY" },
      { name: "Plateau", shortCode: "PL" },
      { name: "Rivers", shortCode: "RI" },
      { name: "Sokoto", shortCode: "SO" },
      { name: "Taraba", shortCode: "TA" },
      { name: "Yobe", shortCode: "YO" },
      { name: "Zamfara", shortCode: "ZA" },
    ],
  },
  {
    countryName: "Pakistan",
    countryShortCode: "PK",
    regions: [
      { name: "Azad Kashmir", shortCode: "JK" },
      { name: "Balochistan", shortCode: "BA" },
      { name: "Gilgit-Baltistan", shortCode: "GB" },
      { name: "Islamabad", shortCode: "IS" },
      { name: "Khaibar Pakhtunkhwa", shortCode: "KP" },
      { name: "Punjab", shortCode: "PB" },
      { name: "Sindh", shortCode: "SD" },
      { name: "Federally Administered Tribal Areas", shortCode: "TA" },
    ],
  },
  {
    countryName: "Philippines",
    countryShortCode: "PH",
    regions: [
      { name: "Autonomous Region in Muslim Mindanao", shortCode: "PH-14" },
      { name: "Bicol", shortCode: "PH-05" },
      { name: "Cagayan Valley", shortCode: "PH-02" },
      { name: "Calabarzon", shortCode: "PH-40" },
      { name: "Caraga", shortCode: "PH-13" },
      { name: "Central Luzon", shortCode: "PH-03" },
      { name: "Central Visayas", shortCode: "PH-07" },
      { name: "Cordillera Administrative Region", shortCode: "PH-15" },
      { name: "Davao", shortCode: "PH-11" },
      { name: "Eastern Visayas", shortCode: "PH-08" },
      { name: "Ilocos", shortCode: "PH-01" },
      { name: "Mimaropa", shortCode: "PH-41" },
      { name: "National Capital Region", shortCode: "PH-00" },
      { name: "Northern Mindanao", shortCode: "PH-10" },
      { name: "Soccsksargen", shortCode: "PH-12" },
      { name: "Western Visayas", shortCode: "PH-06" },
      { name: "Zamboanga Peninsula", shortCode: "PH-09" },
    ],
  },
  {
    countryName: "South Africa",
    countryShortCode: "ZA",
    regions: [
      { name: "Eastern Cape", shortCode: "EC" },
      { name: "Free State", shortCode: "FS" },
      { name: "Gauteng", shortCode: "GT" },
      { name: "KwaZulu-Natal", shortCode: "NL" },
      { name: "Limpopo", shortCode: "LP" },
      { name: "Mpumalanga", shortCode: "MP" },
      { name: "Northern Cape", shortCode: "NC" },
      { name: "North West", shortCode: "NW" },
      { name: "Western Cape", shortCode: "WC" },
    ],
  },
  {
    countryName: "Switzerland",
    countryShortCode: "CH",
    regions: [
      { name: "Aargau", shortCode: "AG" },
      { name: "Appenzell Ausserrhoden", shortCode: "AR" },
      { name: "Appenzell Innerhoden", shortCode: "AI" },
      { name: "Basel-Landschaft", shortCode: "BL" },
      { name: "Basel-Stadt", shortCode: "BS" },
      { name: "Bern", shortCode: "BE" },
      { name: "Fribourg", shortCode: "FR" },
      { name: "Genève", shortCode: "GE" },
      { name: "Glarus", shortCode: "GL" },
      { name: "Graubünden", shortCode: "GR" },
      { name: "Jura", shortCode: "JU" },
      { name: "Luzern", shortCode: "LU" },
      { name: "Neuchâtel", shortCode: "NE" },
      { name: "Nidwalden", shortCode: "NW" },
      { name: "Obwalden", shortCode: "OW" },
      { name: "Sankt Gallen", shortCode: "SG" },
      { name: "Schaffhausen", shortCode: "SH" },
      { name: "Schwyz", shortCode: "SZ" },
      { name: "Solothurn", shortCode: "SO" },
      { name: "Thurgau", shortCode: "TG" },
      { name: "Ticino", shortCode: "TI" },
      { name: "Uri", shortCode: "UR" },
      { name: "Valais", shortCode: "VS" },
      { name: "Vaud", shortCode: "VD" },
      { name: "Zug", shortCode: "ZG" },
      { name: "Zürich", shortCode: "ZH" },
    ],
  },
  {
    countryName: "Taiwan",
    countryShortCode: "TW",
    regions: [
      { name: "Changhua", shortCode: "CHA" },
      { name: "Chiayi", shortCode: "CYQ" },
      { name: "Hsinchu", shortCode: "HSQ" },
      { name: "Hualien", shortCode: "HUA" },
      { name: "Kaohsiung", shortCode: "KHH" },
      { name: "Keelung", shortCode: "KEE" },
      { name: "Kinmen", shortCode: "KIN" },
      { name: "Lienchiang", shortCode: "LIE" },
      { name: "Miaoli", shortCode: "MIA" },
      { name: "Nantou", shortCode: "NAN" },
      { name: "Penghu", shortCode: "PEN" },
      { name: "New Taipei", shortCode: "NWT" },
      { name: "Pingtung", shortCode: "PIF" },
      { name: "Taichung", shortCode: "TXG" },
      { name: "Tainan", shortCode: "TNN" },
      { name: "Taipei", shortCode: "TPE" },
      { name: "Taitung", shortCode: "TTT" },
      { name: "Taoyuan", shortCode: "TAO" },
      { name: "Yilan", shortCode: "ILA" },
      { name: "Yunlin", shortCode: "YUN" },
    ],
  },
  {
    countryName: "Turkey",
    countryShortCode: "TR",
    regions: [
      { name: "Adana", shortCode: "01" },
      { name: "Adiyaman", shortCode: "02" },
      { name: "Afyonkarahisar", shortCode: "03" },
      { name: "Agri", shortCode: "04" },
      { name: "Aksaray", shortCode: "68" },
      { name: "Amasya", shortCode: "05" },
      { name: "Ankara", shortCode: "06" },
      { name: "Antalya", shortCode: "07" },
      { name: "Ardahan", shortCode: "75" },
      { name: "Artvin", shortCode: "08" },
      { name: "Aydin", shortCode: "09" },
      { name: "Balikesir", shortCode: "10" },
      { name: "Bartin", shortCode: "74" },
      { name: "Batman", shortCode: "72" },
      { name: "Bayburt", shortCode: "69" },
      { name: "Bilecik", shortCode: "11" },
      { name: "Bingol", shortCode: "12" },
      { name: "Bitlis", shortCode: "13" },
      { name: "Bolu", shortCode: "14" },
      { name: "Burdur", shortCode: "15" },
      { name: "Bursa", shortCode: "16" },
      { name: "Canakkale", shortCode: "17" },
      { name: "Cankiri", shortCode: "18" },
      { name: "Corum", shortCode: "19" },
      { name: "Denizli", shortCode: "20" },
      { name: "Diyarbakir", shortCode: "21" },
      { name: "Duzce", shortCode: "81" },
      { name: "Edirne", shortCode: "22" },
      { name: "Elazig", shortCode: "23" },
      { name: "Erzincan", shortCode: "24" },
      { name: "Erzurum", shortCode: "25" },
      { name: "Eskisehir", shortCode: "26" },
      { name: "Gaziantep", shortCode: "27" },
      { name: "Giresun", shortCode: "28" },
      { name: "Gumushane", shortCode: "29" },
      { name: "Hakkari", shortCode: "30" },
      { name: "Hatay", shortCode: "31" },
      { name: "Igdir", shortCode: "76" },
      { name: "Isparta", shortCode: "32" },
      { name: "Istanbul", shortCode: "34" },
      { name: "Izmir", shortCode: "35" },
      { name: "Kahramanmaras", shortCode: "46" },
      { name: "Karabuk", shortCode: "78" },
      { name: "Karaman", shortCode: "70" },
      { name: "Kars", shortCode: "36" },
      { name: "Kastamonu", shortCode: "37" },
      { name: "Kayseri", shortCode: "38" },
      { name: "Kilis", shortCode: "79" },
      { name: "Kirikkale", shortCode: "71" },
      { name: "Kirklareli", shortCode: "39" },
      { name: "Kirsehir", shortCode: "40" },
      { name: "Kocaeli", shortCode: "41" },
      { name: "Konya", shortCode: "42" },
      { name: "Kutahya", shortCode: "43" },
      { name: "Malatya", shortCode: "44" },
      { name: "Manisa", shortCode: "45" },
      { name: "Mardin", shortCode: "47" },
      { name: "Mersin", shortCode: "33" },
      { name: "Mugla", shortCode: "48" },
      { name: "Mus", shortCode: "49" },
      { name: "Nevsehir", shortCode: "50" },
      { name: "Nigde", shortCode: "51" },
      { name: "Ordu", shortCode: "52" },
      { name: "Osmaniye", shortCode: "80" },
      { name: "Rize", shortCode: "53" },
      { name: "Sakarya", shortCode: "54" },
      { name: "Samsun", shortCode: "55" },
      { name: "Sanliurfa", shortCode: "63" },
      { name: "Siirt", shortCode: "56" },
      { name: "Sinop", shortCode: "57" },
      { name: "Sirnak", shortCode: "73" },
      { name: "Sivas", shortCode: "58" },
      { name: "Tekirdag", shortCode: "59" },
      { name: "Tokat", shortCode: "60" },
      { name: "Trabzon", shortCode: "61" },
      { name: "Tunceli", shortCode: "62" },
      { name: "Usak", shortCode: "64" },
      { name: "Van", shortCode: "65" },
      { name: "Yalova", shortCode: "77" },
      { name: "Yozgat", shortCode: "66" },
      { name: "Zonguldak", shortCode: "67" },
    ],
  },
  {
    countryName: "United States",
    countryShortCode: "US",
    regions: [
      { name: "Alabama", shortCode: "AL" },
      { name: "Alaska", shortCode: "AK" },
      { name: "American Samoa", shortCode: "AS" },
      { name: "Arizona", shortCode: "AZ" },
      { name: "Arkansas", shortCode: "AR" },
      { name: "California", shortCode: "CA" },
      { name: "Colorado", shortCode: "CO" },
      { name: "Connecticut", shortCode: "CT" },
      { name: "Delaware", shortCode: "DE" },
      { name: "District of Columbia", shortCode: "DC" },
      { name: "Micronesia", shortCode: "FM" },
      { name: "Florida", shortCode: "FL" },
      { name: "Georgia", shortCode: "GA" },
      { name: "Guam", shortCode: "GU" },
      { name: "Hawaii", shortCode: "HI" },
      { name: "Idaho", shortCode: "ID" },
      { name: "Illinois", shortCode: "IL" },
      { name: "Indiana", shortCode: "IN" },
      { name: "Iowa", shortCode: "IA" },
      { name: "Kansas", shortCode: "KS" },
      { name: "Kentucky", shortCode: "KY" },
      { name: "Louisiana", shortCode: "LA" },
      { name: "Maine", shortCode: "ME" },
      { name: "Marshall Islands", shortCode: "MH" },
      { name: "Maryland", shortCode: "MD" },
      { name: "Massachusetts", shortCode: "MA" },
      { name: "Michigan", shortCode: "MI" },
      { name: "Minnesota", shortCode: "MN" },
      { name: "Mississippi", shortCode: "MS" },
      { name: "Missouri", shortCode: "MO" },
      { name: "Montana", shortCode: "MT" },
      { name: "Nebraska", shortCode: "NE" },
      { name: "Nevada", shortCode: "NV" },
      { name: "New Hampshire", shortCode: "NH" },
      { name: "New Jersey", shortCode: "NJ" },
      { name: "New Mexico", shortCode: "NM" },
      { name: "New York", shortCode: "NY" },
      { name: "North Carolina", shortCode: "NC" },
      { name: "North Dakota", shortCode: "ND" },
      { name: "Northern Mariana Islands", shortCode: "MP" },
      { name: "Ohio", shortCode: "OH" },
      { name: "Oklahoma", shortCode: "OK" },
      { name: "Oregon", shortCode: "OR" },
      { name: "Palau", shortCode: "PW" },
      { name: "Pennsylvania", shortCode: "PA" },
      { name: "Puerto Rico", shortCode: "PR" },
      { name: "Rhode Island", shortCode: "RI" },
      { name: "South Carolina", shortCode: "SC" },
      { name: "South Dakota", shortCode: "SD" },
      { name: "Tennessee", shortCode: "TN" },
      { name: "Texas", shortCode: "TX" },
      { name: "Utah", shortCode: "UT" },
      { name: "Vermont", shortCode: "VT" },
      { name: "Virgin Islands", shortCode: "VI" },
      { name: "Virginia", shortCode: "VA" },
      { name: "Washington", shortCode: "WA" },
      { name: "West Virginia", shortCode: "WV" },
      { name: "Wisconsin", shortCode: "WI" },
      { name: "Wyoming", shortCode: "WY" },
      { name: "Armed Forces Americas", shortCode: "AA" },
      {
        name: "Armed Forces Europe, Canada, Africa and Middle East",
        shortCode: "AE",
      },
      { name: "Armed Forces Pacific", shortCode: "AP" },
    ],
  },
  {
    countryName: "Vietnam",
    countryShortCode: "VN",
    regions: [
      { name: "An Giang", shortCode: "44" },
      { name: "Bà Rịa - Vũng Tàu", shortCode: "43" },
      { name: "Bình Dương", shortCode: "57" },
      { name: "Bình Phước", shortCode: "58" },
      { name: "Bình Định", shortCode: "31" },
      { name: "Bình Thuận", shortCode: "40" },
      { name: "Bạc Liêu", shortCode: "55" },
      { name: "Bắc Giang", shortCode: "54" },
      { name: "Bắc Kạn", shortCode: "53" },
      { name: "Bắc Ninh", shortCode: "56" },
      { name: "Bến Tre", shortCode: "50" },
      { name: "Cao Bằng", shortCode: "04" },
      { name: "Cà Mau", shortCode: "59" },
      { name: "Đắk Lắk", shortCode: "33" },
      { name: "Đắk Nông", shortCode: "72" },
      { name: "Điện Biên", shortCode: "71" },
      { name: "Đồng Nai", shortCode: "39" },
      { name: "Đồng Tháp", shortCode: "45" },
      { name: "Gia Lai", shortCode: "30" },
      { name: "Hà Giang", shortCode: "03" },
      { name: "Hà Nam", shortCode: "63" },
      { name: "Hà Tây", shortCode: "15" },
      { name: "Hà Tĩnh", shortCode: "23" },
      { name: "Hải Dương", shortCode: "61" },
      { name: "Hậu Giang", shortCode: "73" },
      { name: "Hòa Bình", shortCode: "14" },
      { name: "Hưng Yên", shortCode: "66" },
      { name: "Khánh Hòa", shortCode: "34" },
      { name: "Kiên Giang", shortCode: "47" },
      { name: "Kon Tum", shortCode: "28" },
      { name: "Lai Châu", shortCode: "01" },
      { name: "Lâm Đồng", shortCode: "35" },
      { name: "Lạng Sơn", shortCode: "09" },
      { name: "Lào Cai", shortCode: "02" },
      { name: "Long An", shortCode: "41" },
      { name: "Nam Định", shortCode: "67" },
      { name: "Nghệ An", shortCode: "22" },
      { name: "Ninh Bình", shortCode: "18" },
      { name: "Ninh Thuận", shortCode: "36" },
      { name: "Phú Thọ", shortCode: "68" },
      { name: "Phú Yên", shortCode: "32" },
      { name: "Quảng Bình", shortCode: "24" },
      { name: "Quảng Nam", shortCode: "27" },
      { name: "Quảng Ngãi", shortCode: "29" },
      { name: "Quảng Ninh", shortCode: "13" },
      { name: "Quảng Trị", shortCode: "25" },
      { name: "Sóc Trăng", shortCode: "52" },
      { name: "Sơn La", shortCode: "05" },
      { name: "Tây Ninh", shortCode: "37" },
      { name: "Thái Bình", shortCode: "20" },
      { name: "Thái Nguyên", shortCode: "69" },
      { name: "Thanh Hóa", shortCode: "21" },
      { name: "Thừa Thiên–Huế", shortCode: "26" },
      { name: "Tiền Giang", shortCode: "46" },
      { name: "Trà Vinh", shortCode: "51" },
      { name: "Tuyên Quang", shortCode: "07" },
      { name: "Vĩnh Long", shortCode: "49" },
      { name: "Vĩnh Phúc", shortCode: "70" },
      { name: "Yên Bái", shortCode: "06" },
      { name: "Cần Thơ", shortCode: "CT" },
      { name: "Đà Nẵng", shortCode: "DN" },
      { name: "Hà Nội", shortCode: "HN" },
      { name: "Hải Phòng", shortCode: "HP" },
      { name: "Hồ Chí Minh (Sài Gòn)", shortCode: "SG" },
    ],
  },
];

export default countryList;
